### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by CarpiendoChacra** [vinayak-7-0-3/AIO-Music-Helper#21]
Hello, Very good code.
My problem is that I don't download from tidal, I tried several ways and I couldn't solve it, it says that the downloaded file cannot be found in ./bot/DOWNLOADS/NONE/5848

I tried authenticating and everything and it doesn't work for me. I don't know why it will be from now on, thanks. Very happy with your work

Deezer downloads me well

**Comment by vinayak-7-0-3** [comment]
Can you check the authentication status of Tidal in the Bot settings panel.
And also can you share the Tidal link you are trying to download.

**Comment by CarpiendoChacra** [comment]
![image](https://user-images.githubusercontent.com/123395455/223696888-351eac55-5b26-49bc-9652-ada71e69056a.png)

http://www.tidal.com/track/160041283

It's very strange I'm going to keep trying because I don't understand why it doesn't download.

It is translated into Spanish but everything continues as is the code.

With qobuz it throws me this error too
I use virtual environment for the libraries

[Errno 22] Invalid argument: './bot/DOWNLOADS/qobuz/58733/En La Intimidad | CROSSOVER #1.flac'

The strange thing is that albums download fine from Tidal, but individual tracks don't. maybe that will help
The same happens with Qobuz, download
albums but not individual tracks

**Comment by CarpiendoChacra** [comment]
It already works for me, the bot also triggers the CPU at 100% or only in ubuntu does that happen?   

RAM 8 GB
VCPU 4
DISK LOCAL 160 GB

**Comment by vinayak-7-0-3** [comment]
> ![image](https://user-images.githubusercontent.com/123395455/223696888-351eac55-5b26-49bc-9652-ada71e69056a.png)
> 
> http://www.tidal.com/track/160041283
> 
> It's very strange I'm going to keep trying because I don't understand why it doesn't download.
> 
> It is translated into Spanish but everything continues as is the code.
> 
> With qobuz it throws me this error too I use virtual environment for the libraries
> 
> [Errno 22] Invalid argument: './bot/DOWNLOADS/qobuz/58733/En La Intimidad | CROSSOVER #1.flac'
> 
> The strange thing is that albums download fine from Tidal, but individual tracks don't. maybe that will help The same happens with Qobuz, download albums but not individual tracks

Ok,
The issue is in my code. Rather than using a regex pattern, I've used a simple list to check the links.
The links you've tried starts with 'http' and what I've added starts with 'https'.
**So just changing the links to https will fix the issue for now**

And ignore the 100% CPU usage as my coding isn't efficient XD

**Comment by CarpiendoChacra** [comment]
Another query friend, how can I solve that when more than 2 users are using at the same time the bot does not respond? Thanks in advance. For example, 2 friends are downloading 1 album of 12 songs, the bot no longer responds to me.

**Comment by vinayak-7-0-3** [comment]
> Another query friend, how can I solve that when more than 2 users are using at the same time the bot does not respond? Thanks in advance. For example, 2 friends are downloading 1 album of 12 songs, the bot no longer responds to me.

Maybe thats due to high process load and slow bandwidth
