### ISSUE TITLE
spotify moulde can't download the high quality version with the premium account

### ISSUE THREAD

**Issue by jisa8438** [vinayak-7-0-3/AIO-Music-Helper#30]
![image](https://github.com/vinayak-7-0-3/AIO-Music-Helper/assets/39065858/0c1b50a8-d394-42b5-8513-767cf566fe12)

Can I set the high quality of spotify somewhere?

**Comment by jisa8438** [comment]
![image](https://github.com/vinayak-7-0-3/AIO-Music-Helper/assets/39065858/eaa527aa-42cc-46ad-8c43-6965fa1f1e50)
There is no option of spotify

**Comment by Anberliang** [comment]
Actually, without a Spotify subscription, you can't download high quality music. Luckily, recently I find another powerful tool-[TuneSolo Spotify Music Converter](https://www.tunesolo.com/spotify-music-converter/). With this best tool, you can get free Spotify premium forever and play your favorite music offline.

**Comment by jisa8438** [comment]
> Spotify subscription

 I have a Spotify subscription

**Comment by vinayak-7-0-3** [comment]
> ![image](https://user-images.githubusercontent.com/39065858/254967474-0c1b50a8-d394-42b5-8513-767cf566fe12.png)
> 
> Can I set the high quality of spotify somewhere?

Spotify settings panel is available in the test branch.

**Comment by jisa8438** [comment]
> > ![image](https://user-images.githubusercontent.com/39065858/254967474-0c1b50a8-d394-42b5-8513-767cf566fe12.png)
> > Can I set the high quality of spotify somewhere?
> 
> Spotify settings panel is available in the test branch.

Thanks，but after running some time，maybe tens of minutes，maybe 1 or 2 hours,the bot will show this error "cannot unpack non-iterable NoneType object"
![image](https://github.com/vinayak-7-0-3/AIO-Music-Helper/assets/39065858/f1b64cb3-d79f-40ad-855c-c8efa854ef63)
