### ISSUE TITLE
  in the alpha branch，auth button of tidal panel can’t be used

### ISSUE THREAD

**Issue by jisa8438** [vinayak-7-0-3/AIO-Music-Helper#31]
![image](https://github.com/vinayak-7-0-3/AIO-Music-Helper/assets/39065858/21512f5e-4ad1-48c8-a5cd-1789dfc2662a)
in the alpha branch，when i click on auth button，there is no response
it‘ normal in the main branch version

**Comment by vinayak-7-0-3** [comment]
Fixed in #32 (test branch)
